name: event-crawl-schedule

on:
  schedule:
    # TEST: UTC 22:17 = KST 07:17
    - cron: '17 22 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    uses: ./.github/workflows/_crawl-jobs.yml
    secrets: inherit
